[Fixes #993] Use createLayer configuration to show the create dataset action
GeoNode/geonode-mapstore-client pull request #1002
Opened 2022-05-30 15:53 UTC by DavidQuartz

2022-05-31 12:48 UTC, allyoucanmap requested changes

2022-05-31 12:48 UTC, allyoucanmap commented on geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
> +                            "config": "createLayer",
@DavidQuartz could we try to use disableIf instead to add a new param?

`"disableIf": "{((state('settings') && state('settings').createLayer) ? true : false)}",`

I did not test this so please try it locally if it works

2022-06-06 07:54 UTC, allyoucanmap approved these changes

2022-06-06 07:54 UTC, merged

2022-06-06 08:05 UTC, allyoucanmap commented
please @marthamareal test this on dev when the new bundle is merged and let us know if we can backport on the stable branch 4.x

2022-06-06 09:09 UTC, marthamareal commented
@DavidQuartz, Am testing this locally since it's where I can easily update `CREATE_LAYER` setting

I have the setting set to false, however, I can see the `create dataset` link
![ss1](https://user-images.githubusercontent.com/20810749/172131416-cd14a1f7-a388-4b24-8411-abada299d257.png)

2022-06-06 10:35 UTC, marthamareal commented
@DavidQuartz, It seems my local environment was not reflecting the changes. After uninstalling and re-installing the client. Tests for this issue passed as expected. It can be safely backported to 4.x.