[Backport 4.x][Fixes 925 & 1018] The upload box should accept xml and sld files along with the dataset itself
GeoNode/geonode-mapstore-client pull request #1032
Opened 2022-06-15 15:33 UTC by DavidQuartz

This PR includes xml and sld metadata files. Those files, if present, must have the same name as the dataset files, else cannot be uploaded.
XML and SLD are not submitted as base_file in upload

2022-06-20 12:45 UTC, allyoucanmap requested changes
@DavidQuartz There are some conflicts to resolve, thanks

2022-06-20 12:46 UTC, allyoucanmap requested changes
@DavidQuartz There are some conflicts to resolve, thanks

2022-06-20 13:43 UTC, DavidQuartz commented
> @DavidQuartz There are some conflicts to resolve, thanks

@allyoucanmap resolved

2022-06-21 10:34 UTC, allyoucanmap approved these changes

2022-06-21 10:34 UTC, merged