[Fixes 1022] Thumbnail placeholders
GeoNode/geonode-mapstore-client pull request #1142
Opened 2022-08-05 10:47 UTC by DavidQuartz

The current grey box has been replaced with a nice-looking default thumbnail.
For resource cards 
<img width="351" alt="Screenshot 2022-08-05 at 10 16 52" src="https://user-images.githubusercontent.com/42542676/183061486-b7a5a749-a132-4aa1-bbac-bc44a6b68667.png">

For Info Panel (when user has no edit permission)
<img width="782" alt="Screenshot 2022-08-05 at 10 17 45" src="https://user-images.githubusercontent.com/42542676/183061661-6ade1ba4-2a44-4cc8-8e2e-dc6e142ee897.png">

For info panel (when user has edit permission) a base64 image of a white background has been used in the interim, to preserve the Thumnbnail component from Mapstore
<img width="772" alt="Screenshot 2022-08-05 at 10 17 54" src="https://user-images.githubusercontent.com/42542676/183061906-0575cf04-63ea-4c01-83a7-adc9374c1fa1.png">

2022-08-05 11:00 UTC, allyoucanmap approved these changes

2022-08-05 12:14 UTC, allyoucanmap requested changes

2022-08-05 12:14 UTC, allyoucanmap commented on geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
> +import { getResourceTypesInfo, getMetadataDetailUrl, ResourceTypes, GXP_PTYPES, getResourceImageSource } from '@js/utils/ResourceUtils';
@DavidQuartz I don't see this getResourceImageSource  function in ResourceUtils

2022-08-18 09:35 UTC, allyoucanmap approved these changes

2022-08-18 09:35 UTC, merged

2022-08-18 09:36 UTC, allyoucanmap commented
@marthamareal please test on dev and let us know if we can backport to 4.x branch

2022-08-19 09:56 UTC, marthamareal commented
@DavidQuartz This can be backported