[Fixes 1249] Change Edit Layer style to Edit style
GeoNode/geonode-mapstore-client pull request #1251
Opened 2022-10-19 13:28 UTC by DavidQuartz

'Edit Layer Style' has been changed to 'Edit Style' in ActionNav bar in resource view pages.
A new translation has been added for 'Edit Layer Style' for visual style editor plugin

2022-10-20 08:58 UTC, giohappy requested changes

2022-10-20 08:58 UTC, giohappy commented on geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
> +            "editLayerStyle": "Edit Layer style",
Edit Dataset style

2022-10-20 08:58 UTC, giohappy commented on geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
> +            "editLayerStyle": "Modifica stile di livello",
Modifica lo stile del dataset

2022-10-20 13:13 UTC, giohappy approved these changes

2022-10-20 13:13 UTC, merged

2022-10-21 10:10 UTC, DavidQuartz commented
@marthamareal please test on master and let us know if we can backport on 4.0.x, thanks

2022-11-08 08:57 UTC, giohappy commented
@DavidQuartz I just tested this and it looks ok, except "style" is lowercase, while the other menu items have the second term uppercase. I would fix this before merging to 4.0.x.

![image](https://user-images.githubusercontent.com/571129/200520097-f95ec3b2-6658-4132-97f2-5f190b746504.png)