#1416: Display relationships between resources in the details info panel
GeoNode/geonode-mapstore-client pull request #1418
Opened 2023-04-24 16:50 UTC by dsuren1

### Description
This PR adds the possibility to show linked resources tab when resource has linked resources

### Issue
- #1416 

### Screenshot
<img width="455" alt="image" src="https://user-images.githubusercontent.com/26929983/234062281-5fa485cf-c70f-471a-a8e1-aa1c796d8f8d.png">

2023-04-27 16:44 UTC, allyoucanmap requested changes
@dsuren1 The implementation looks fine, just some minor changes.
I'm not sure if I cover all the replacement for resourceTypesInfo so please double check and please let me know if it makes sense for you this change

2023-04-27 16:44 UTC, allyoucanmap commented on geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
> +    'attributes': null,
let's remove this one

```suggestion
```

2023-04-27 16:44 UTC, allyoucanmap commented on geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
> +    types
```suggestion
    resourceTypesInfo
```

2023-04-27 16:44 UTC, allyoucanmap commented on geonode_mapstore_client/client/js/components/DetailsPanel/DetailsRelatedResources.jsx
> +    types: {}
```suggestion
    resourceTypesInfo: {}
```

2023-04-28 07:42 UTC, giohappy requested changes
@dsuren1 sorry about that but we changed our mind again. Let's rename "related resources" to "linked resources", for the variables names, the component, etc. 
It's more natural and it will make it easier to map the client to the backend properties.

2023-04-28 10:57 UTC, dsuren1 commented on geonode_mapstore_client/client/js/api/geonode/v2/index.js
> +    return axios.get(parseDevHostname(`${endpoints[RESOURCES]}/${pk}/linked_resources`))
@giohappy 
The api throws following error when setting params `{page: 1, page_size: 99999}`. Could you please look into it
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/26929983/235130100-42af2341-6c46-4a90-85d2-a8d18ee16c2d.png">

2023-04-28 14:00 UTC, allyoucanmap approved these changes

2023-04-28 14:22 UTC, allyoucanmap requested changes

2023-04-28 14:22 UTC, allyoucanmap commented on geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
> +            "relatedResources": "Linked Resources"
This should be changed to linkedResources

2023-04-28 16:25 UTC, giohappy commented on geonode_mapstore_client/client/js/api/geonode/v2/index.js
> +    return axios.get(parseDevHostname(`${endpoints[RESOURCES]}/${pk}/linked_resources`))
@dsuren1 the fix has been merged and it's been deployed to development demo

2023-05-02 07:46 UTC, allyoucanmap approved these changes

2023-05-02 07:49 UTC, giohappy approved these changes

2023-05-02 07:49 UTC, merged

2023-05-02 14:10 UTC, giohappy commented
@gannebamm we're already on it. @mattiagiupponi is implementing the reverse relationships to show up inside linked resources.

2023-05-02 14:15 UTC, mattiagiupponi commented
@gannebamm @giohappy 
The issue is available here: https://github.com/GeoNode/geonode/issues/10993
And it's related PR is here waiting for review: https://github.com/GeoNode/geonode/pull/10994
Any hint is welcome

2023-05-02 14:39 UTC, giohappy commented
@gannebamm deployed to demo if you want to test it

![image](https://user-images.githubusercontent.com/571129/235699663-8cd78745-caaf-4f54-8e36-61b498f16c59.png)

2023-05-02 16:43 UTC, gannebamm commented
That was fast 😄 
Now it is working as expected (https://development.demo.geonode.org/catalogue/#/dataset/1003):
![grafik](https://user-images.githubusercontent.com/6172324/235730636-a3d0283e-c4a7-4f4b-9b91-26dac9b140f3.png)

awesome!