#1477 - Document creation from external URL
GeoNode/geonode-mapstore-client pull request #1479
Opened 2023-06-26 06:11 UTC by dsuren1

### Description
This PR adds new feature to upload document via external URL

### Issue
- #1477 
<img width="314" alt="image" src="https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/bea2cdb0-a8f0-4026-8c74-db212eb267d0">

2023-07-06 08:06 UTC, allyoucanmap requested changes
- [ ] clicking multiple time on the add url generates this error in console
![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/c4810bee-0e53-4e3f-8edd-8a58de5d2966)
- [ ] added a unsupported format such as .svg. The ext is disabled but the user does not get warning and the upload is disabled
![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/cd80a5cb-84bc-4397-94e8-d495c0b307a3)

Note if we try to upload via file we get the warning, the behaviour should be the same
![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/247cf9b2-fe0e-49ba-b3a1-06bb4a61cc35)

for dataset if the upload is incomplete we add an exclamation mark and a small description of what missing

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/1e6f940d-fce9-4bf7-80fd-8316b4fde00b)

so if possible we should have all warning set and visible, in addition if not too complex I would also align the size of the extension select input with the other

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/a0c63f04-98a3-46f5-8010-2a002a7674a4)

2023-07-06 13:30 UTC, dsuren1 commented
**Updated**
<img width="321" alt="Screenshot 2023-07-06 at 6 51 38 PM" src="https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/96d7445c-5359-46f8-aa6e-0a545359a384">

2023-07-06 16:35 UTC, allyoucanmap requested changes
@dsuren1 Sent a commit with some style updated so please pull the latest changes

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/e2453d47-2a63-45c3-b79e-7e437d288125)

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/89b86350-3f4d-4b47-bfaa-b8e8cb8ef364)

I found this problem

- [ ] issue with not supported extensions
  - add a new document url
  - add an svg eg https://development.demo.geonode.org/static/mapstore/img/geonode-logo.svg
  - upload is blocked because the extension is not supported but the extension selection is still available even if it does not have effect
https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/98fb56ae-fec5-453b-91f3-b0e43eca6a2f

2023-07-06 16:35 UTC, allyoucanmap commented on geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
> +            "duplicateUrl": "URL is already present in the list of uploads",
Please update all translations with:
`This URL is already present in the list of uploads`

2023-07-07 05:32 UTC, dsuren1 commented
> I found this problem
> 
> * [ ]  issue with not supported extensions
>   * add an svg eg https://development.demo.geonode.org/static/mapstore/img/geonode-logo.svg
>   * upload is blocked because the extension is not supported but the extension selection is still available even if it does not have effect

This issue is happening after the style change commit, looks like disabled class was removed. I will add it back

2023-07-10 07:48 UTC, allyoucanmap approved these changes

2023-07-10 07:48 UTC, merged