#1493: Improve faceting and add facet filtering
GeoNode/geonode-mapstore-client pull request #1496
Opened 2023-07-17 12:53 UTC by dsuren1

### Description
This PR implements the following
- https://github.com/GeoNode/geonode-mapstore-client/issues/1493 and 
- https://github.com/GeoNode/geonode-mapstore-client/issues/1494

2023-07-21 08:37 UTC, allyoucanmap requested changes

2023-07-21 08:37 UTC, allyoucanmap commented on geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
> +const replaceGlobal = (labelId) => labelId === "global" ? "Global" : labelId;
Please remove this and related check

2023-07-25 09:56 UTC, dsuren1 commented
PR will be moved to ready when depedant API issue is deployed

2023-07-28 07:26 UTC, allyoucanmap approved these changes

2023-07-28 07:27 UTC, merged