Added table of content to open layer details in map view.
GeoNode/geonode-mapstore-client pull request #1661
Opened 2024-01-25 08:14 UTC by ahmdthr

Resolves https://github.com/GeoNode/geonode-mapstore-client/issues/1660

A new button to view layer details is added on the map view.

2024-01-25 10:40 UTC, ridoo commented
@ahmdthr the PR still is marked as draft .. if this is intended, though, please ignore my comment

2024-03-07 09:58 UTC, ridoo commented
@ahmdthr this one would have to be aligned to the latest changes of linked resources

2024-03-19 10:28 UTC, ridoo commented
Thanks @ahmdthr 

@giohappy the PR is now ready for review on your side

2024-05-07 13:35 UTC, dsuren1 commented
@ahmdthr Kindly resolve the conflicts and align the code changes with the latest changes in master. Thanks!

2024-05-17 10:47 UTC, gannebamm commented
@giohappy Sorry @ahmdthr was busy with other tasks and we need some additional days to sort out our ressources. Are we to late for lending a helping hand? @dsuren1 already did some changes and requested a review.

2024-05-17 14:37 UTC, giohappy commented
I've tested the PR locally. The idea is good and it's really useful, but I have a few concerns:

 - every time a layer is selected in the TOC a new API request is sent to obtain the required information to enable (or not) the info button for the layer
 - the information that has been retrieved is not saved, so the same request is sent again every time a layer is selected

I think this could be improved if the following is implemented:

 - The response can be stored, somehow, inside the state of the component. This avoids making the same request for the same layer multiple times
 - But, the real point is: **are these calls really needed**? We already query both the map and the datasets endpoint when the map is loaded. Much information about datasets is retrieved at that time. Isn't this enough? If more attributes are required we can add them to the response of those requests, instead of making additional calls.

@gannebamm @ahmdthr if you agree I would consider these improvements before merging it. In that case the PR should be marked as `Draft` for the time being.

2024-05-29 09:33 UTC, giohappy requested changes
see https://github.com/GeoNode/geonode-mapstore-client/pull/1661#issuecomment-2117753350

2024-08-22 07:56 UTC, ahmdthr commented
> I've tested the PR locally. The idea is good and it's really useful, but I have a few concerns:
> 
> * every time a layer is selected in the TOC a new API request is sent to obtain the required information to enable (or not) the info button for the layer
> * the information that has been retrieved is not saved, so the same request is sent again every time a layer is selected
> 
> I think this could be improved if the following is implemented:
> 
> * The response can be stored, somehow, inside the state of the component. This avoids making the same request for the same layer multiple times
> * But, the real point is: **are these calls really needed**? We already query both the map and the datasets endpoint when the map is loaded. Much information about datasets is retrieved at that time. Isn't this enough? If more attributes are required we can add them to the response of those requests, instead of making additional calls.
> 
> @gannebamm @ahmdthr if you agree I would consider these improvements before merging it. In that case the PR should be marked as `Draft` for the time being.

@giohappy Thank you very much for your comments. The only reason a new request was being made was because the linked resources were not included in the batch request. Now with recent changes, it is no longer necessary to sent a request to fetch linked resources. I am currently working on it and expect the final version of the PR shortly.

2024-11-07 09:43 UTC, ahmdthr commented
The info button for layers on the maps page now fetches all data including linked resources with a single call. Additionally, the linked resources are stored in state such that re-fetching is not necessary when re selecting one layer again.

2024-11-25 14:11 UTC, giohappy commented
@dsuren1 please do a new review.

2024-11-26 06:00 UTC, dsuren1 commented on geonode_mapstore_client/client/js/epics/index.js
> +            const layerResourceDataset = state.gnresource.data.maplayers.find(mapLayer => mapLayer.dataset.pk === parseInt(layerResourceId, 10)).dataset;
Error when `data` is empty

2024-11-26 06:02 UTC, dsuren1 requested changes
@ahmdthr 
It seems in some cases, an error is being generated in `gnFetchMissingLayerData` when selecting a layer, which is impacting further testing and review of this PR. 

<img width="541" alt="image" src="https://github.com/user-attachments/assets/5e77d22b-3067-413b-aca1-e42cad0b42a8">

Could you please check and update the PR? Thank you!

2024-11-29 05:51 UTC, ahmdthr commented
@dsuren1 Thank you very much for your review. All the problems stemmed from non-existent referencing of properties, and I have fixed it in the latest commit. Please have a look at it again and let me know. Thank you.

2024-12-03 08:38 UTC, dsuren1 requested changes
@ahmdthr 
Overall the changes looks good. But I see some minor issues as mentioned below. Kindly check it out

- Layer detail doesn't always reflect correct layer name on the detail panel

  https://github.com/user-attachments/assets/3fbcb9b8-3d02-4e18-bb4c-bbafd80f2b82

2024-12-03 08:38 UTC, dsuren1 commented on geonode_mapstore_client/static/mapstore/configs/localConfig.json
> +                "name": "LayerDetailViewer",
```suggestion
                "mandatory": true,
                "name": "LayerDetailViewer",
```

In order to make the plugin available by default add `mandatory: true`, or add it to pluginsConfig under `TOC` as `children`, so the user can select the plugin when adding `viewer` to map.

Currently, the plugin is not available on map with viewer existing already.

2024-12-03 14:44 UTC, ahmdthr commented
> @ahmdthr Overall the changes looks good. But I see some minor issues as mentioned below. Kindly check it out
> 
> * Layer detail doesn't always reflect correct layer name on the detail panel
>   
>     
>       
>       
>   
>       layer_detail_sync.mp4

This bug where the title of the dataset on the detail layer was not being changed was due to the fact that the "EditTtile" component was using its own state for the title, thus changing the "resource" did not update the title if the "DetailsPanel" was already inflated. It is fixed now.

2024-12-04 11:48 UTC, dsuren1 approved these changes

2024-12-04 11:51 UTC, ridoo commented
@dsuren1 great to see you approved the PR .. any chance to see this PR backported to `4.4.x`?

2024-12-04 11:56 UTC, merged