Client - Misalignment between inline language selector and brand Navbar items #145
GeoNode/geonode-mapstore-client pull request #188
Opened 2021-05-20 15:01 UTC by MuhweziDeo

Fix small misalignment when language selector is in inline mode

2021-05-25 09:40 UTC, allyoucanmap requested changes
The inline option can be added in static/mapstore/configs/localConfig.json at the path `geoNodeConfiguration.theme.languageSelector.inline` for testing pourpose

```js
"geoNodeConfiguration": {
    "theme": {
        // ...,
        "languageSelector": {
            "inline": true
        }
    },
```

2021-05-25 09:40 UTC, allyoucanmap commented on geonode_mapstore_client/client/themes/geonode/scss/_action-navbar.scss
> +            .inline {
this selector is not valid for the class name you composed before

2021-05-25 09:40 UTC, allyoucanmap commented on geonode_mapstore_client/client/themes/geonode/scss/_action-navbar.scss
> +                padding-right: 2.8rem;
If I try to test this value in the dev tool this is the resoult
![image](https://user-images.githubusercontent.com/19175505/119475708-aa2adf80-bd4d-11eb-8617-71ec42f576a3.png)

The value should be 0.5rem instead

2021-05-25 09:44 UTC, allyoucanmap requested changes

2021-05-25 10:24 UTC, MuhweziDeo commented on geonode_mapstore_client/client/js/components/home/LanguageSelector.jsx
> +            className={`gn-language-selector ${inline} ? 'inline' : ''`}
I do not know how I didnot see this

2021-05-31 08:02 UTC, allyoucanmap approved these changes

2021-06-03 09:30 UTC, merged